### ISSUE TITLE
MissingReferenceException

### ISSUE THREAD

**Issue by sasa42** [modanhan/Unity-Lens-Flare-2019#1]
Hi,

the LensFlare is moving but console spawns

MissingReferenceException: The object of type 'RenderTexture' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Aerobox.Rendering.PostProcessing.FlareRenderer.Release () (at Assets/Flare/Flare.cs:69)
UnityEngine.Rendering.PostProcessing.PostProcessBundle.Release () (at C:/Users/q237091/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.postprocessing@2.1.6/PostProcessing/Runtime/PostProcessBundle.cs:43)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnDisable () (at C:/Users/q237091/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.postprocessing@2.1.6/PostProcessing/Runtime/PostProcessLayer.cs:355)
UnityEditor.SceneView:OnDisable()

Tested in Unity 2019.2.14f1, PostProcessing 2.1.6
 and        Unity  2019.1.0f2

**Comment by modanhan** [comment]
Hi, thanks for bringing up this issue. Please review this patch https://github.com/modanhan/Unity-Lens-Flare-2019/pull/2

**Comment by modanhan** [comment]
Should be fixed with this [patch].(https://github.com/modanhan/Unity-Lens-Flare-2019/pull/2)
