### ISSUE TITLE
Failed to open source file: 'PostProcessing/Shaders/StdLib.hlsl' at line 7 (on d3d11)

### ISSUE THREAD

**Issue by local306** [modanhan/Unity-Lens-Flare-2019#3]
Trying to add this to a project using Unity 2019.3.6f1 and getting this when I add it to my post profile:

`Shader error in 'Hidden/Aerobox/Flare': failed to open source file: 'PostProcessing/Shaders/StdLib.hlsl' at line 7 (on d3d11)

Compiling Fragment program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR`

**Comment by local306** [comment]
Thanks @modanhan! Tried it out this morning and it works!

**Comment by modanhan** [comment]
Good to hear!
